server:
    servlet:
        context-path: ${BASE_URL:/}
    port: ${PORT:3800}

spring:
    application:
        name: litrarr
    thymeleaf:
        cache: false
    datasource:
        url: "jdbc:sqlite:${app.path.config}/litrarr.db"
        driver-class-name: org.sqlite.JDBC
    jpa:
        database-platform: "org.hibernate.community.dialect.SQLiteDialect"
    flyway:
        baseline-on-migrate: true
    security:
        user:
            name: ${APP_USER:admin}
            password: ${APP_PASSWORD:admin}

logging:
    level:
        root: ${LOGGING_LEVEL:INFO}

app:
    path:
        config: "${CONFIG_PATH:/config}"
        download: "${DOWNLOAD_PATH:/downloads}"
        library: "${LIBRARY_PATH:/library}"
    user-agent: ${USER_AGENT:Litrarr/1.0}
    api-keys:
        google-books: ${GOOGLE_BOOKS_API_KEY:}
        comic-vine: ${COMIC_VINE_API_KEY:}
        mal-client-id: ${MYANIMELIST_API_KEY:}

